In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
pwd

'C:\\Users\\rakei'

In [3]:
pwd

'C:\\Users\\rakei'

In [4]:
os.chdir(r"C:\Users\rakei\PEP1.csv")

NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\rakei\\PEP1.csv'

In [ ]:

pwd

In [17]:
data=pd.read_csv('PEP1.csv')

In [18]:
z=data.shape

In [19]:
z

(1460, 81)

In [20]:
data.isnull().all

<bound method NDFrame._add_numeric_operations.<locals>.all of          Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0     False       False     False        False    False   False   True
1     False       False     False        False    False   False   True
2     False       False     False        False    False   False   True
3     False       False     False        False    False   False   True
4     False       False     False        False    False   False   True
...     ...         ...       ...          ...      ...     ...    ...
1455  False       False     False        False    False   False   True
1456  False       False     False        False    False   False   True
1457  False       False     False        False    False   False   True
1458  False       False     False        False    False   False   True
1459  False       False     False        False    False   False   True

      LotShape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
0        False        False      False  ...     False    True   True
1        False        False      False  ...     False    True   True
2        False        False      False  ...     False    True   True
3        False        False      False  ...     False    True   True
4        False        False      False  ...     False    True   True
...        ...          ...        ...  ...       ...     ...    ...
1455     False        False      False  ...     False    True   True
1456     False        False      False  ...     False    True  False
1457     False        False      False  ...     False    True  False
1458     False        False      False  ...     False    True   True
1459     False        False      False  ...     False    True   True

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice
0            True    False   False   False     False          False      False
1            True    False   False   False     False          False      False
2            True    False   False   False     False          False      False
3            True    False   False   False     False          False      False
4            True    False   False   False     False          False      False
...           ...      ...     ...     ...       ...            ...        ...
1455         True    False   False   False     False          False      False
1456         True    False   False   False     False          False      False
1457        False    False   False   False     False          False      False
1458         True    False   False   False     False          False      False
1459         True    False   False   False     False          False      False

[1460 rows x 81 columns]>

In [21]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [22]:
1460-1202

258

In [23]:
?pd

In [24]:
data.columns.unique()

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchebvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functiol', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [25]:
catagorical=data.select_dtypes(exclude=[np.number])
numeric=data.select_dtypes(include=[np.number])

In [26]:
print(catagorical)

     MSZoning Street Alley LotShape LandContour Utilities LotConfig LandSlope  \
0          RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
1          RL   Pave   NaN      Reg         Lvl    AllPub       FR2       Gtl
2          RL   Pave   NaN      IR1         Lvl    AllPub    Inside       Gtl
3          RL   Pave   NaN      IR1         Lvl    AllPub    Corner       Gtl
4          RL   Pave   NaN      IR1         Lvl    AllPub       FR2       Gtl
...       ...    ...   ...      ...         ...       ...       ...       ...
1455       RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
1456       RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
1457       RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
1458       RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
1459       RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl

     Neighborhood Condition1  ... GarageType GarageFinish GarageQual  \
0         CollgCr       Norm  ...     Attchd          RFn         TA
1         Veenker      Feedr  ...     Attchd          RFn         TA
2         CollgCr       Norm  ...     Attchd          RFn         TA
3         Crawfor       Norm  ...     Detchd          Unf         TA
4         NoRidge       Norm  ...     Attchd          RFn         TA
...           ...        ...  ...        ...          ...        ...
1455      Gilbert       Norm  ...     Attchd          RFn         TA
1456       NWAmes       Norm  ...     Attchd          Unf         TA
1457      Crawfor       Norm  ...     Attchd          RFn         TA
1458          mes       Norm  ...     Attchd          Unf         TA
1459      Edwards       Norm  ...     Attchd          Fin         TA

     GarageCond PavedDrive PoolQC  Fence MiscFeature SaleType SaleCondition
0            TA          Y    NaN    NaN         NaN       WD        Normal
1            TA          Y    NaN    NaN         NaN       WD        Normal
2            TA          Y    NaN    NaN         NaN       WD        Normal
3            TA          Y    NaN    NaN         NaN       WD       Abnorml
4            TA          Y    NaN    NaN         NaN       WD        Normal
...         ...        ...    ...    ...         ...      ...           ...
1455         TA          Y    NaN    NaN         NaN       WD        Normal
1456         TA          Y    NaN  MnPrv         NaN       WD        Normal
1457         TA          Y    NaN  GdPrv        Shed       WD        Normal
1458         TA          Y    NaN    NaN         NaN       WD        Normal
1459         TA          Y    NaN    NaN         NaN       WD        Normal

[1460 rows x 43 columns]

In [27]:
data.shape

(1460, 81)

In [28]:
numeric

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [29]:
38+43

81

In [30]:
#nunique() gives the number of unique item
#unique() gives the unique items
for col in data.columns:
    print('no of unique values in',col,data[col].nunique())

no of unique values in Id 1460
no of unique values in MSSubClass 15
no of unique values in MSZoning 5
no of unique values in LotFrontage 110
no of unique values in LotArea 1073
no of unique values in Street 2
no of unique values in Alley 2
no of unique values in LotShape 4
no of unique values in LandContour 4
no of unique values in Utilities 2
no of unique values in LotConfig 5
no of unique values in LandSlope 3
no of unique values in Neighborhood 25
no of unique values in Condition1 9
no of unique values in Condition2 8
no of unique values in BldgType 5
no of unique values in HouseStyle 8
no of unique values in OverallQual 10
no of unique values in OverallCond 9
no of unique values in YearBuilt 112
no of unique values in YearRemodAdd 61
no of unique values in RoofStyle 6
no of unique values in RoofMatl 8
no of unique values in Exterior1st 15
no of unique values in Exterior2nd 16
no of unique values in MasVnrType 4
no of unique values in MasVnrArea 327
no of unique values in ExterQual 4
no of unique values in ExterCond 5
no of unique values in Foundation 6
no of unique values in BsmtQual 4
no of unique values in BsmtCond 4
no of unique values in BsmtExposure 4
no of unique values in BsmtFinType1 6
no of unique values in BsmtFinSF1 637
no of unique values in BsmtFinType2 6
no of unique values in BsmtFinSF2 144
no of unique values in BsmtUnfSF 780
no of unique values in TotalBsmtSF 721
no of unique values in Heating 6
no of unique values in HeatingQC 5
no of unique values in CentralAir 2
no of unique values in Electrical 5
no of unique values in 1stFlrSF 753
no of unique values in 2ndFlrSF 417
no of unique values in LowQualFinSF 24
no of unique values in GrLivArea 861
no of unique values in BsmtFullBath 4
no of unique values in BsmtHalfBath 3
no of unique values in FullBath 4
no of unique values in HalfBath 3
no of unique values in BedroomAbvGr 8
no of unique values in KitchebvGr 4
no of unique values in KitchenQual 4
no of unique values in TotRmsAbvGrd 12
no of unique values in Functiol 7
no of unique values in Fireplaces 4
no of unique values in FireplaceQu 5
no of unique values in GarageType 6
no of unique values in GarageYrBlt 97
no of unique values in GarageFinish 3
no of unique values in GarageCars 5
no of unique values in GarageArea 441
no of unique values in GarageQual 5
no of unique values in GarageCond 5
no of unique values in PavedDrive 3
no of unique values in WoodDeckSF 274
no of unique values in OpenPorchSF 202
no of unique values in EnclosedPorch 120
no of unique values in 3SsnPorch 20
no of unique values in ScreenPorch 76
no of unique values in PoolArea 8
no of unique values in PoolQC 3
no of unique values in Fence 4
no of unique values in MiscFeature 4
no of unique values in MiscVal 21
no of unique values in MoSold 12
no of unique values in YrSold 5
no of unique values in SaleType 9
no of unique values in SaleCondition 6
no of unique values in SalePrice 663

In [31]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [32]:
?data.describe